configs:
  galaxy.yml:
    galaxy:
      admin_users: suderman@jhu.edu,afgane@gmail.com
      master_api_key: galaxypassword
      brand: AWS

# Temporary values for the development
jobs:
  rules:
    tpv_rules_local.yml:
      destinations:
        k8s:
          max_cores: 1
          max_mem: 4

ingress:
  enabled: true
  ingressClassName: ""
  canary:
    enabled: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: ~
    paths:
    - path: /galaxy
  path: /galaxy

persistence:
  storageClass: nfs
  size: 20Gi

cvmfs:
  deployPostInstallFix: true
  cvmfscsi:
    cache:
      local:
        enabled: true
        pvc:
          storageClass: nfs
          name: cvmfs-local-cache
      alien:
        enabled: false
        pvc:
          name: cvmfs-alien-cache
    logVerbosityLevel: 5

postgresql:
  persistence:
    storageClass: nfs

rabbitmq:
  persistence:
    storageClassName: nfs
