---
- hosts: controllers[0]
  collections:
    - kubernetes.core
  vars:
    persistence_storage_class: block_storage
    size: "10Gi"
    default: false
    allow_expansion: true
    reclaim: Delete
    version: 1.8.0
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
  tasks:
    - name: Install openshift
      pip:
        name: openshift
        state: present
        extra_args: "--break-system-packages"
    - name: Create the NFS namespace
      k8s:
        kind: Namespace
        name: nfs-provisioner
        state: present
    - name: Install the Ganesha NFS Helm repository
      helm_repository:
        name: nfs-ganesha
        repo_url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
        state: present
    - name: Helm install Ganesha NFS
      helm:
        name: nfs-provisioner
        namespace: nfs-provisioner
        chart_ref: nfs-ganesha/nfs-server-provisioner
        chart_version: "{{ version }}"
        values:
          persistence:
            enabled: true
            storageClass: "{{ persistence_storage_class }}"
            size: "{{ size }}"
          storageClass:
            create: true
            defaultClass: "{{ default }}"
            allowVolumeExpansion: "{{ allow_expansion }}"
            reclaimPolicy: "{{ reclaim }}"
