---
- name: Basic setup of the node
  hosts: nodes
  tasks:
    - name: Install system packages
      ansible.builtin.apt:
        name: "{{ install_packages }}"
        state: present
        update_cache: true
      become: true
      vars:
        install_packages: "{{ base_packages + (gcp_packages if kube_cloud_provider == 'gcp' else []) }}"
        base_packages:
          - python3
          - python3-pip
          - nfs-common
        gcp_packages:
          - golang
    - name: Check if the instance needs a reboot.
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: f
    - name: Reboot if needed
      ansible.builtin.reboot:
      become: true
      when: f.stat.exists
