---
- hosts: nodes
  tasks:
    - name: Install system packages
      apt:
        name: "{{ install_packages }}"
        state: present
        update_cache: yes
      become: true
      vars:
        install_packages: "{{ base_packages + (gcp_packages if kube_cloud_provider == 'gcp' else []) }}"
        base_packages:
          - python3
          - python3-pip
          - nfs-common
        gcp_packages:
          - golang
    - name: Install openshift
      pip:
        name: openshift
        state: present
        extra_args: "--break-system-packages"
    - name: Check if the instance needs a reboot.
      stat:
        path: /var/run/reboot-required
      register: f
    - name: Reboot if needed
      reboot:
      become: yes
      when: f.stat.exists
