---
- name: Basic setup of the node
  hosts: nodes
  tasks:
    - name: Install system packages
      ansible.builtin.apt:
        name: "{{ install_packages }}"
        state: present
        update_cache: true
      become: true
      vars:
        install_packages:
          - python3
          - python3-pip
          - python3-openshift  # Required by the Ansible Kubernetes module
          - nfs-common

    - name: Check if the instance needs a reboot.
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: f

    - name: Reboot if needed
      ansible.builtin.reboot:
      become: true
      when: f.stat.exists
