---
- name: Setup storage
  hosts: controllers[0]
  vars:
    cluster_hostname: galaxy
    kubeconfig: ~/.kube/config
    cinder_csi_version: 2.31.2
    block_storage_disk_path: /mnt/block_storage
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
  tasks:
    - name: Render the hostpath storage class template
      kubernetes.core.k8s:
        template:
          path: templates/hostpath_storage_class.yaml.j2
        state: present

    - name: Render the elastic block storage class
      kubernetes.core.k8s:
        template:
          path: block_storage_storageclass.yml.j2
        state: present

    - name: Create csi-drivers namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: csi-drivers
        state: present
